__title__ = 'buildstock-batch'
__description__ = 'Executing BuildStock projects on batch infrastructure.'
__url__ = 'http://github.com/NREL/buildstockbatch'
__version__ = '0.6'
__author__ = 'Noel Merket'
__author_email__ = 'noel.merket@nrel.gov'
__license__ = 'BSD-3'
__copyright__ = 'Copyright 2018 The Alliance for Sustainable Energy'
