# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import os

here = os.path.abspath(os.path.dirname(__file__))
metadata = {}

with open(os.path.join(here, "..", "buildstockbatch", "__version__.py"), "r", encoding="utf-8") as f:
    exec(f.read(), metadata)

# -- Project information -----------------------------------------------------

project = metadata["__title__"]
copyright = metadata["__copyright__"]
author = metadata["__author__"]

# The short X.Y version
version = metadata["__version__"]
# The full version, including alpha/beta/rc tags
release = metadata["__version__"]


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinxcontrib.programoutput",
    "changelog",
    "sphinx_paramlinks",
]

changelog_sections = [
    "general",
    "schema",
    "comstock",
    "sampler",
    "workflow",
    "resstock",
    "eagle",
    "local",
    "aws",
    "postprocessing",
    "documentation",
]
# tags to sort on inside of sections
changelog_inner_tag_sort = ["feature", "changed", "removed", "bug", "moved"]


# how to render changelog links
changelog_render_ticket = "http://www.github.com/nrel/buildstockbatch/issues/%s"

changelog_render_pullreq = {"default": "https://www.github.com/nrel/buildstockbatch/pull/%s"}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_theme_path = [
    "_themes",
]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "BuildStockBatchdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "BuildStockBatch.tex",
        "BuildStock Batch Documentation",
        "Noel Merket (NREL)",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "buildstockbatch", "BuildStock Batch Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "BuildStockBatch",
        "BuildStock Batch Documentation",
        author,
        "BuildStockBatch",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Ignore warnings ---------------------------------------------------------

# Ignore reference targets not found
nitpick_ignore = [
    ("py:func", "BuildStockBatchBase.validate_precomputed_sample"),
    ("py:func", "BuildStockBatchBase.validate_xor_nor_schema_keys"),
    ("py:func", "EagleBatch.run_building"),
    ("py:class", "sampler.CommercialSobolSingularitySampler"),
    ("py:class", "sampler.CommercialSobolDockerSampler"),
    ("py:class", "workflow_generator.CommercialDefaultWorkflowGenerator"),
    ("py:class", "sampler.PrecomputedSampler"),
    ("py:class", "sampler.BuildStockSampler"),
    ("py:class", "BuildStockBatchBase"),
    ("py:func", "BuildStockBatchBase.run_sampling"),
]
